-- AlterTable
ALTER TABLE "Propiedad" ALTER COLUMN "superficie" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "latitud" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "longitud" SET DATA TYPE DOUBLE PRECISION;
